name: 'GitHub Actions Ping Bot'

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Install node'
        uses: actions/setup-node@v1
      - name: 'Install NPM dependencies'
        run: npm install
      - name: 'Run code'
        run: node index.js
        env:
          SLACK_WEBHOOK_SECRET: ${{ secrets.SLACK_WEBHOOK_SECRET }}
